### ISSUE TITLE
Cannot hook to i386 apps after upgrade to 10.12

### ISSUE THREAD

**Issue by eminarcissus** [w0lfschild/mySIMBL#9]
I've created a plugin to hook into a 32bit only app working on SIMBL, since the app is written with i386 so I can only run the plugin in i386 mode, after upgrade to sierra and updated to the latest SIMBL, I found seems like it starts to failed to load i386 plugins and start to alert me like this, how can I work with it?

Error loading /System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL:  dlopen(/System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL, 262): no suitable image found.  Did find:
	/System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL: mach-o, but wrong architecture
32BIT_APP: OpenScripting.framework - can't find entry point InjectEventHandler in scripting addition /System/Library/ScriptingAdditions/SIMBL.osax.

**Comment by eminarcissus** [comment]
I managed to recompile SIMBL framework with Universal and it works as normal

**Comment by khrisanfov** [comment]
@eminarcissus how did you do it? I had a compilation error when I changed architecture.
